trigger:
  branches:
    include:
      - main  # Or your working branch

pool:
  name: 'stephquizfour'  # Replace with your actual pool name

steps:
  - checkout: self

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      options: '-B'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkDirectory: 'C:\\Program Files\\Java\\jdk-21'  # Double backslashes for Windows path
      mavenVersionOption: 'Default'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target'
      ArtifactName: 'drop'
      publishLocation: 'Container'
